# Generated by Django 2.1.2 on 2018-10-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181011_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_timestamp',
            field=models.DateTimeField(blank=True, verbose_name='修改时间'),
        ),
    ]
