# Generated by Django 2.1.2 on 2018-10-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181016_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='app.Tag', verbose_name='文章标签'),
        ),
    ]
